// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoGKcKqtQQMV_NLhzAXphtjjn3pyRl2k0',
    appId: '1:469393954960:web:e91b03ed3dcaf27cc7a015',
    messagingSenderId: '469393954960',
    projectId: 'bizmanager-93c0d',
    authDomain: 'bizmanager-93c0d.firebaseapp.com',
    storageBucket: 'bizmanager-93c0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZa5RuKy6JZikWjL_QD1Bt82bg2gYolQ',
    appId: '1:469393954960:android:90062939f12acc1ac7a015',
    messagingSenderId: '469393954960',
    projectId: 'bizmanager-93c0d',
    storageBucket: 'bizmanager-93c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDMOlJEGvw1sszPiENML2QrsRGFyT3w2w',
    appId: '1:469393954960:ios:55f9b37ae4dce607c7a015',
    messagingSenderId: '469393954960',
    projectId: 'bizmanager-93c0d',
    storageBucket: 'bizmanager-93c0d.firebasestorage.app',
    iosBundleId: 'com.example.bizmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDMOlJEGvw1sszPiENML2QrsRGFyT3w2w',
    appId: '1:469393954960:ios:55f9b37ae4dce607c7a015',
    messagingSenderId: '469393954960',
    projectId: 'bizmanager-93c0d',
    storageBucket: 'bizmanager-93c0d.firebasestorage.app',
    iosBundleId: 'com.example.bizmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoGKcKqtQQMV_NLhzAXphtjjn3pyRl2k0',
    appId: '1:469393954960:web:af06f607221e521dc7a015',
    messagingSenderId: '469393954960',
    projectId: 'bizmanager-93c0d',
    authDomain: 'bizmanager-93c0d.firebaseapp.com',
    storageBucket: 'bizmanager-93c0d.firebasestorage.app',
  );
}
